name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV
      - uses: dentarg/fly@v1
        with:
          build-args: "RUBY_VERSION=${{ env.RUBY_VERSION }}"
          fly-token: ${{ secrets.FLY_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
